platform :ios, '9.1'
target '陈叙文仿网易新闻' do
pod 'SDWebImage','~>3.7'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFNetworking', '~> 3.0’
pod 'OpenShare', '~> 0.0.1'
pod 'FMDB', '~> 2.6.2'
end